---
root: true

parserOptions:
  ecmaVersion: latest

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:import/typescript'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
  - 'prettier'

env:
  browser: true
  node: true
  jest: true

rules:
  no-console: 0
  import/extensions: 0
  new-cap:
    - error
    - properties: false
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor:
        - req
        - reply
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
  quotes: ['error', 'single']
  # игнорируем неиспользуемые переменные с префиксом _
  no-unused-vars: ['warn', { 'argsIgnorePattern': '^_' }]
  object-curly-newline:
    - error
    - multiline: true
      consistent: true
  import/order: ['error', { 'newlines-between': 'always', 'alphabetize': { 'order': 'asc', 'caseInsensitive': true } }]

ignorePatterns:
  - dist/*
  - node_modules/
  - README.md
